### ISSUE TITLE
Auto-Add new Hosts

### ISSUE THREAD

**Issue by strowi** [GRIF-IRFU/puppet-omd#10]
Hi,

i am currently testing this module over my own modifications to erwbgy/puppet-check_mk.
So far it seems very comfortable. But  i am missing one very handy feature: the possibility to auto-add new hosts (by creating the config virtually on the client-side and export it to the server) .

**Comment by fschaer** [comment]
sudo calls were replaced with "su -c", fixing 3. Closing (please reopen if you feel the issue was not correcty/entirely handled)

Regards
