### ISSUE TITLE
class concat::setup error

### ISSUE THREAD

**Issue by bbhenry** [GRIF-IRFU/puppet-omd#15]
Hi,

I am trying to install OMD server with what's suggested and the following error showed up.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class concat::setup
```

**Comment by fschaer** [comment]
Do you have puppetlabs concat <= 1.2.1 in your modulepath ?

**Comment by bbhenry** [comment]
no, I installed the latest today and I can now see why that didn't work
either. Thanks for the reply.
