### ISSUE TITLE
Nagios plugin not showing on the graph

### ISSUE THREAD

**Issue by SergiuCip** [GRIF-IRFU/puppet-omd#19]
Hi, as I have mentioned in my last commented, I have successfully install OMD on Ubuntu 14.04 and also I have developed a module which gathers the Hiera data and applies it. However, I have a slight issue which is, I am installing the Nagios: check_phpfpm_status plugin (https://github.com/regilero/check_phpfpm_status/blob/master/check_phpfpm_status.pl) and everything works fine. However, I am expecting when I go to PNP4Nagios to see the graphs for that service(s), however, nothing it is displayed apart from the ones that are already there.

Am I missing something?

Thank you,

Kind regards,
Sergiu

**Comment by fschaer** [comment]
Hi,

I am not the check author, and therefore I do now know how/why the performance data would be output or wrong.

With omd, performance data works "as is", I did not change that part of the config.
If needed, you can always change OMD configuration variables in your installation, and then re-introduce the changes in puppet when you found what you were looking for - in that case, either in the nagios plugin doc, or in the official check_mk documentation .

Regards
