### ISSUE TITLE
request: add alias to host

### ISSUE THREAD

**Issue by kveerman** [GRIF-IRFU/puppet-omd#20]
at the moment hostname and alias are the same. But it would be great if these could be different. Like you can configure it through wato

**Comment by fschaer** [comment]
I think this can be configured using the ipaddresses check_mk variable, I'd have to test it to validate.
But the thing is : where/how would you like to setup the alias ?
Using an exported resource, or by declaring it statically in the omd main configuration ?

In the first case, I'm wondering from where the info could come (apparently nothing usefull in facter) ... any use case ?

**Comment by kveerman** [comment]
could be static config
its just translating the ugly name (pdxxx) to something userfriendly (rabbit01.p)
depending on what you need to do name or alias can be best to use.
eg: dns config is based on the pdxxx names, but applications connect with the userfriendly name

if its already possible it would be great. 
You have an example for me how to do it??

**Comment by fschaer** [comment]
Took me some time to try out…

So, it appears you can set aliases like this in check_mk :
   extra_host_conf["alias"] = []
   extra_host_conf["alias"] += [("mytest" , ["node69.datagrid.cea.fr"])]

Appending to an empty key or variable breaks check_mk/python, we therefore have to set the var empty first – or set it with all of the aliases in one line, but I think people would prefer appendeing whatever they want to put in those variables…
This then translates in the puppet module with :
    omd::check_mk::var::set {'extra_host_conf#alias': site=>'test', content=>'[]' }
    omd::check_mk::var::append {'extra_host_conf#alias|1': site=>'test', content=>'[("myalias" , ["my real hostname"])]' }

I’ll add this in the Readme …

**Comment by kveerman** [comment]
k. that'll work. would have been nice to be able to add it in the same spot as add_host.

**Comment by fschaer** [comment]
I’ll see what I can do ;)
