### ISSUE TITLE
$svc_provider='init' raises "Provider init is not functional on this host" on centos7

### ISSUE THREAD

**Issue by Melkor333** [GRIF-IRFU/puppet-omd#31]
With the new changes which include a service provider, I can't deploy omd on my centos7 machine anymore and get this message:
```
Error: /Stage[main]/Omd/Service[omd]: Provider init is not functional on this host
```
It works, when I change the line 36 in the file manifest/init.pp to either 'systemd', 'undef' or 'redhat', or when I delete the entire line.
```
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -33,7 +33,7 @@ class omd(
     'RedHat': {
       $omd_service = 'omd'
       $dbi_pkg = 'libdbi'
-      $svc_provider='init'
(+      $svc_provider='systemd')
       if( 0+$::operatingsystemmajrelease >= 6 ) {
         require epel
       }
```

From what I understand from the official [puppet docs](https://docs.puppet.com/puppet/latest/reference/types/service.html#service-provider-redhat), it will automatically use 'redhat' for maj version <7 and 'systemd' for version >=7.

In my opinion, we could remove this line, what do you think?

**Comment by fschaer** [comment]
Hmm…

It’s working on my production CentOS 7.2 host…
What’s your puppet version (client/master/server) ?

**Comment by Melkor333** [comment]
Master: 4.6.0
Client: 4.6.1

**Comment by Melkor333** [comment]
Did you have problems when the variable wasn't set? The mentioned docs say:

> The specific backend to use for this service resource. You will seldom need to specify this —
> Puppet will usually discover the appropriate provider for your platform.

If it works for you without specifying the variable, I would say we can savely delete it.

**Comment by fschaer** [comment]
Ah, then that’s the issue…
Looks like puppet4 disabled the init provider somehow, but the redhat one still seems to be there.
I think we can’t use system, since the latest OMD I’ve seen weren’t shipping with a systemd unit file – or we could probably ship one if willing to use system, but I haven’t tested

So, the easy fix is to replace init with redhat, the real fix would be to use system with a unit file

**Comment by fschaer** [comment]
We crossed mails.
So yes, I faced issues : on CentOS 7, the default provider is system, but the omd RPM isn’t system compatible, that’s why this provider thing is in the templates

**Comment by Melkor333** [comment]
In my centos version systemd automatically finds the init script and uses it with the help of the [systemd-sysv-generator](https://www.freedesktop.org/software/systemd/man/systemd-sysv-generator.html). But I think it would still be better to use 'redhat', as I don't know if this feature is enabled everywhere and how long it will be available..
