### ISSUE TITLE
Apache can't find /test/check_mk/index.py

### ISSUE THREAD

**Issue by Melkor333** [GRIF-IRFU/puppet-omd#33]
When I deploy omd with ssl, I get a 404 Error, because it can't find the proper directory of the webpage (saying 'The requested URL /check_mk/index.py was not found on this server.')
When I add the following Line to the `/etc/httpd/conf/httpd.conf` of my node, it works:
```
IncludeOptional "/omd/apache/*.conf
```

My node definition looks like that:

```
node 'testserver' {
  class { 'apache': default_ssl_vhost => true }
  include omd
  omd::site {'test': }
  omd::site::user { 'test':
    site =>'test',
    privileges=>'admin',
    pass_md5=>'HVSJ.h631LfUw'
  }
  class { omd::ssl::vhost:
    sites=>['test'],
    port => 443,
    ssl_cert => '/etc/httpd/ssl/apache.cr',
    ssl_key => '/etc/httpd/ssl/apache.key',
    ca_dir => '/etc/httpd/ssl/',
    ssl_force_client_cert => false, 
    priority => '15',
  }
}
```

How have you been able to get it to include the directory of your omd installation without defining it in the puppet module? Am I missing something?

**Comment by fschaer** [comment]
Hmmm… Strange…
I have this file :
# cat /etc/httpd/conf.d/zzz_omd.conf
# Include Apache configuration of OMD sites
IncludeOptional /omd/apache/*.conf

I don’t think I deployed it with puppet, it came with omd. Aren’t you seeing any puppet error ?

**Comment by Melkor333** [comment]
Not errors, but it seems as if the apache module wants to delete those files:
```
...
Notice: /Stage[main]/Apache/File[/etc/httpd/conf.d/welcome.conf]/ensure: removed
Notice: /Stage[main]/Apache/File[/etc/httpd/conf.d/zzz_omd.conf]/ensure: removed
...
```

I tried requiring the apache modules, but this didn't change anything. I find it strange that it removes the files on my setup, but doesn't on yours. Which apache module version have you installed? Mine is 1.10.0

**Comment by fschaer** [comment]
Ahhhh... ok, got it. I actually had this file managed somewhere else in my config... I just pushed the missing part into master. I would be glad if you could confirm the fix, then I would close this issue...

**Comment by Melkor333** [comment]
Ok, thanks! It's fixed now!
